// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import DeleteTaskController from "./delete_task_controller"
// application.register("delete-task", DeleteTaskController)

// import DisableCardController from "./disable_card_controller"
// application.register("disable-card", DisableCardController)

import TaskController from "./task_controller"
application.register("task", TaskController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
